<?php

/**
 * Implements hook_uninstall().
 */
function booking_calendar_uninstall() {
  variable_del('booking_calendar_book_table');
  variable_del('booking_calendar_names_courts');
  variable_del('booking_hours_settings');
  unset($_SESSION['tables']);
  unset($_SESSION['current_select']);
  unset($_SESSION['table_hours']);
  unset($_SESSION['hours_settings']);
  unset($_SESSION['client_hours']);
}