<?php

/**
 * @file
 * Main finctions for booking calendar.
 */

/**
 * Implements hook_menu().
 */
function booking_calendar_menu() {
  $items['admin/config/content/booking_calendar'] = array(
    'page callback' => 'booking_calendar_admin_settings',
    'access arguments' => array('administer booking calendar'),
    'type' => MENU_CALLBACK,
  );
  $items['booking/calendar/ajax'] = array(
    'page callback' => 'booking_calendar_month_ajax',
    'access arguments' => array('administer booking calendar'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function booking_calendar_permission() {
  return array(
    'administer booking calendar' => array(
      'title' => t('Administer the Booking Calendar'),
      'description' => t('Allow users use Booking Calendar'),
    ),
  );
}


/**
 * Defines form callback for the admin/config/availability-calendar/settings
 * page.
 */
function booking_calendar_admin_settings() {

  drupal_add_js(drupal_get_path('module', 'booking_calendar') . '/js/calendar.js');
  drupal_add_css(drupal_get_path('module', 'booking_calendar') . '/css/calendar.css');

  $output = '';
  $output .= '<div id="t3"></div>';
  $output .= '<div class="flags">
                <ul>
                    <li class="this"><span class="av">' . t('Pasiekiamas') . '</span></li>
                    <li><span class="na">' . t('Pilnai nubaustas') . '</span></li>
                    <li><span class="opt">' . t('Pašalinti nubaustas') . '</span></li>
                </ul>
            </div>';

  $output .= '<div id="calendar-wrapper">';

  $output .= theme('booking_calendar_admin', array('week' => _booking_calendar_calculate()));

  $output .= '</div>';


  $hours = array();

  $hour_begin = 8;

  $minutes = 0;

  $interval = 30;

  for ($i = 0; $i < 30; $i++) {
    $hours[$i] = date('H : i', mktime($hour_begin, $minutes, 0, date('n'), date('j'), date('Y')));
    $minutes += $interval;

  }


  $courts = _default_hours_and_name_courts();

  if (!empty(variable_get('booking_calendar_names_courts', ''))) {
    $courts = variable_get('booking_calendar_names_courts', '');
  }

  array_unshift($courts, array('name' => t('TIME')));

  $court_form = drupal_get_form('booking_calendar_courts_form');
  $courts_form_html = render($court_form);

  $output .= $courts_form_html;

  $output .= '<table id="booking-courts"><thead><tr>';
  foreach ($courts as $court) {
    if (!empty($court['name'])) {
      $output .= '<td>' . $court['name'] . '</td>';
    }
    else {
      $output .= '<td></td>';
    }
  }
  $output .= '</tr></thead>';
  foreach ($hours as $hour) {
    $output .= '<tr>';

    $a = 0;
    foreach ($courts as $court) {

      if ($a == 0) {
        $output .= '<td>' . $hour . '</td>';
      }
      else {
        if ($court['name']) {
          $hour_key = str_replace(' : ', '_', $hour);
          $output .= '<td>' . $court['hours'][$hour_key]['price'] . '€' . '</td>';
        }
      }
      $a++;
    }
    '</tr>';
  }
  $output .= '</table>';

  return $output;
}


function booking_calendar_courts_form($form, &$form_state) {

  $courts = _default_hours_and_name_courts();

  if (empty(variable_get('booking_calendar_names_courts', ''))) {
    variable_set('booking_calendar_names_courts', $courts);
  }
  else {
    $courts = variable_get('booking_calendar_names_courts', '');
  }

  $form['courts'] = array(
    '#type' => 'fieldset',
    '#title' => t('Courts settings'),
    '#weight' => 5,
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );

  $form['courts']['names'] = array(
    '#type' => 'fieldset',
    '#title' => t('Courts names'),
    '#weight' => 2,
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );


  $form['courts']['actions'] = array(
    '#type' => 'fieldset',
    '#title' => t('Courts actions'),
    '#weight' => 3,
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );

  $form['courts']['actions']['delete'] = array(
    '#type' => 'fieldset',
    '#title' => t('Courts delete'),
    '#weight' => 3,
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );

  $form['courts']['actions']['add'] = array(
    '#type' => 'fieldset',
    '#title' => t('Courts add'),
    '#weight' => 3,
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );

  foreach ($courts as $court) {
    $form['courts']['names']['name']['name-' . $court['name']] = array(
      '#type' => 'textfield',
      '#title' => t('Name court'),
      '#default_value' => $court['name'],
      '#size' => 60,
      '#maxlength' => 128,
    );

    $form['courts']['prices']['price']['price-' . $court['name']] = array(
      '#type' => 'fieldset',
      '#title' => t('Courts prices') . ' ' . $court['name'],
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
    );


    $hours = array();

    $hour_begin = 8;
    $minutes = 0;
    $interval = 30;

    for ($i = 0; $i < 30; $i++) {
      $hours[$i] = date('H : i', mktime($hour_begin, $minutes, 0, date('n'), date('j'), date('Y')));
      $minutes += $interval;
    }

    foreach ($hours as $hour) {
      $hour_key = str_replace(' : ', '_', $hour);
      $form['courts']['prices']['price']['price-' . $court['name']][$court['name'] . '_' . $hour_key] = array(
        '#type' => 'textfield',
        '#title' => t('Price court ') . $court['name'] . '  ' . $hour,
        '#default_value' => $court['hours'][$hour_key]['price'],
        '#size' => 60,
        '#maxlength' => 128,
      );
    }


    $form['courts']['actions']['delete'] = array(
      '#type' => 'submit',
      '#value' => t('Delete court '),
      '#attributes' => array('class' => array('delete-form')),
    );
    $form['courts']['actions']['add'] = array(
      '#type' => 'submit',
      '#value' => t('Add court '),
      '#attributes' => array('class' => array('add-form')),
    );
  }


  $form['submit_button'] = array(
    '#type' => 'submit',
    '#value' => t('Click Here!'),
  );

  return $form;
}

function booking_calendar_courts_form_submit($form, &$form_state) {


  if (empty(variable_get('booking_calendar_names_courts', ''))) {
    $courts_default = _default_hours_and_name_courts();
  }
  else {
    $courts_default = variable_get('booking_calendar_names_courts', '');
  }

  $courts_final = array();

  foreach ($courts_default as $court_default) {

    foreach ($court_default['hours'] as $hour) {//dsm($hour);

      $hour_key = str_replace(' : ', '_', $hour['hour']);

      $hours_prices[$hour_key] = array(
        'hour' => $hour['hour'],
        'price' => $form_state['values'][$court_default['name'] . '_' . $hour_key],
      );
      $courts_final[$court_default['name']] = array(
        'name' => $court_default['name'],
        'hours' => $hours_prices,
      );
    }
  }
  variable_set('booking_calendar_names_courts', $courts_final);


}


function _default_hours_and_name_courts() {
  $hours = array();

  $hour_begin = 8;
  $minutes = 0;
  $interval = 30;

  for ($i = 0; $i < 30; $i++) {
    $hours[$i] = date('H : i', mktime($hour_begin, $minutes, 0, date('n'), date('j'), date('Y')));
    $minutes += $interval;
  }

  // Define default values.
  $courts = array();

  $price_u1 = 0;
  $price_u2 = 0;
  $price_u3 = 0;
  $price_u4 = 0;

  $courts = array(
    1 => array(
      'name' => 'U1',
      'price' => $price_u1,
    ),
    2 => array(
      'name' => 'U2',
      'price' => $price_u2,
    ),
    3 => array(
      'name' => 'U3',
      'price' => $price_u3,
    ),
    4 => array(
      'name' => 'U4',
      'price' => $price_u4,
    ),
  );

  $courts_final = array();

  foreach ($courts as $court) {
    foreach ($hours as $hour) {
      $hours_prices[$hour] = array(
        'hour' => $hour,
        'price' => 0,
      );
      $courts_final[$court['name']] = array(
        'name' => $court['name'],
        'hours' => $hours_prices,
      );
    }
  }
  return $courts_final;
}


/**
 * Implements hook_theme().
 */
function booking_calendar_theme($existing, $type, $theme, $path) {
  return array(
    'booking_calendar_admin' => array(
      'variables' => array(
        'week' => NULL,
        'month' => NULL,
        'year' => NULL,
      ),
    ),
    'booking_calendar_admin_table_day_hours' => array(
      'variables' => array(
        //'week' => NULL,
        //'month' => NULL,
        //'year' => NULL,
      ),
    ),
  );
}

function theme_booking_calendar_admin_table_day_hours($variables) {

}

/**
 * Themes the availability calendar field.
 */
function theme_booking_calendar_admin($variables) {

  isset($variables['week']) ? $week = $variables['week'] : $week = _calendar_calculate();;
  isset($variables['month']) ? $month = $variables['month'] : $month = date('n');
  isset($variables['year']) ? $year = $variables['year'] : $year = date('Y');

  $month_name = date('F', mktime(0, 0, 0, $month, date("j"), date('Y')));

  // Translate months.
  switch ($month_name) {
    case 'January' :
      $month_name = 'Sausis';
      break;
    case 'February' :
      $month_name = 'Vasaris';
      break;
    case 'March' :
      $month_name = 'Kovas';
      break;
    case 'April' :
      $month_name = 'Balandis';
      break;
    case 'May' :
      $month_name = 'Gegužė';
      break;
    case 'June' :
      $month_name = 'Birželis';
      break;
    case 'July' :
      $month_name = 'Liepa';
      break;
    case 'August' :
      $month_name = 'Rugpjūtis';
      break;
    case 'September' :
      $month_name = 'Rugsėjis';
      break;
    case 'October' :
      $month_name = 'Spalis';
      break;
    case 'November' :
      $month_name = 'Lapkritis';
      break;
    case 'December' :
      $month_name = 'Gruodis';
      break;
  }


  // 3. Print the contents of the array $ week
  // A calendar
  // Display the table.
  $output = '<div class="year">' . $year . '</div>
             <div id="controls">
                <div data-year="' . $year . '" data-month="' . $month . '" class="prev">' . t('Ankstesnis') . '</div><div class="month">' . $month_name . '</div><div  data-year="' . $year . '" data-month="' . $month . '" class="next">' . t('Kitas') . '</div></div>';
  $output .= '<table id="booking-calendar"><thead>';

  $output .= '<thead><tr>';
  for ($i = 6; $i < 13; $i++) {

    $output .= '<td>' . date('l', mktime(0, 0, 0, date('m'), $i, $year)) . '</td>';
  }

  $output .= '</tr></thead>';
  for ($i = 0; $i < count($week); $i++) {
    $output .= "<tr>";
    for ($j = 0; $j < 7; $j++) {
      if (!empty($week[$i][$j])) {

        // If you are dealing with a Saturday and Sunday
        // highlights them.

        if ($j == 5 || $j == 6) {
          $classes = 'weekends';
          if ($week[$i][$j] == date('j')) {
            $classes = 'this weekends';
          }
        }
        elseif ($week[$i][$j] == date('j')) {
          $classes = 'this';
        }
        else {
          $classes = '';
        }
        if (isset($_SESSION['tables'])) {
          foreach ($_SESSION['tables'][$year][$month] as $key => $value) {
            if (!empty($_SESSION['tables'][$year][$month][$key])) {
              if ($j == $_SESSION['tables'][$year][$month][$key]['week_j'] && $i == $_SESSION['tables'][$year][$month][$key]['week_i']) {
                $classes = $_SESSION['tables'][$year][$month][$key]['chan'];
              }
            }
          }
        }
        else {
          $booking_table = variable_get('booking_calendar_book_table', '');
          if (!empty($booking_table)) {
            foreach ($booking_table[$year][$month] as $key => $value) {
              if (!empty($booking_table[$year][$month][$key])) {
                if ($j == $booking_table[$year][$month][$key]['week_j'] && $i == $booking_table[$year][$month][$key]['week_i']) {
                  $classes = $booking_table[$year][$month][$key]['chan'];
                }
              }
            }
          }

        }
        $output .= '<td week_i="' . $i . '" week_j = "' . $j . '" class="' . $classes . '">' . $week[$i][$j] . '</td>';
      }
      else {
        $output .= "<td>&nbsp;</td>";
      }
    }
    $output .= "</tr>";
  }
  $output .= "</table>";

  return $output;
}

/**
 * @return mixed
 * Calculate calendar arrays.
 */
function _booking_calendar_calculate() {

  // We calculate the number of days in the current month.
  $dayofmonth = date('t');
  // Counter for the days of the month.
  $day_count = 1;

  $month = date('n');

  $week = array();

  // 1. The first week.
  $num = 0;
  for ($i = 0; $i < 7; $i++) {
    // Calculate the number of days of the week for the number of.
    $dayofweek = date('w', mktime(0, 0, 0, $month, $day_count, date('Y')));

    // Leads to a number of the format 1 - Monday, ..., 6 - Saturday.
    $dayofweek = $dayofweek - 1;
    if ($dayofweek == -1) {
      $dayofweek = 6;
    }

    if ($dayofweek == $i) {
      // If the same days of the week,
      // Fill the array $week
      // Number of months.
      $week[$num][$i] = $day_count;
      $day_count++;
    }
    else {
      $week[$num][$i] = "";
    }
  }

  // 2. The following week of the month.
  while (TRUE) {
    $num++;
    for ($i = 0; $i < 7; $i++) {
      $week[$num][$i] = $day_count;
      $day_count++;
      // If you have reached the end of the month - leave
      // The loop.
      if ($day_count > $dayofmonth) {
        break;
      }
    }
    // If you have reached the end of the month - leave
    // From the cycle.
    if ($day_count > $dayofmonth) {
      break;
    }
  }
  return $week;
}


/**
 * Ajax callback.
 */
function booking_calendar_month_ajax() {
  if (count($_POST)) {
    // We calculate the number of days in the current month.
    $dayofmonth = date('t');
    // Counter for the days of the month.
    $day_count = 1;

    isset($_POST['day']) ? $day = $_POST['day'] : $day = date('j');

    isset($_POST['month_number']) ? $month = $_POST['month_number'] : $month = date('n');

    isset($_POST['year']) ? $year = $_POST['year'] : $year = date('Y');

    isset($_POST['table']) ? $table = json_decode($_POST['table']) : $table = array();

    $table = (array) $table;

    // Save values in session
    $_SESSION['tables'][$year][$month][$day] = $table;
    $booking_tables = $_SESSION['tables'];

    // If session is expired save value in database
    variable_set('booking_calendar_book_table', $booking_tables);

    // 1. The first week.
    $num = 0;
    for ($i = 0; $i < 7; $i++) {
      // Calculate the number of days of the week for the number of.
      $dayofweek = date('w', mktime(0, 0, 0, $month, $day_count, $year));

      // Leads to a number of the format 1 - Monday, ..., 6 - Saturday.
      $dayofweek = $dayofweek - 1;
      if ($dayofweek == -1) {
        $dayofweek = 6;
      }

      if ($dayofweek == $i) {
        // If the same days of the week,
        // Fill the array $week
        // Number of months.
        $week[$num][$i] = $day_count;
        $day_count++;
      }
      else {
        $week[$num][$i] = "";
      }
    }

    // 2. The following week of the month.
    while (TRUE) {
      $num++;
      for ($i = 0; $i < 7; $i++) {
        $week[$num][$i] = $day_count;
        $day_count++;
        // If you have reached the end of the month - leave
        // The loop.
        if ($day_count > $dayofmonth) {
          break;
        }
      }
      // If you have reached the end of the month - leave
      // From the cycle.
      if ($day_count > $dayofmonth) {
        break;
      }
    }

    $output = theme('booking_calendar_admin', array(
      'week' => $week,
      'month' => $month,
      'year' => $year,
    ));
    $response = array(
      'output' => $output,
    );

    return drupal_json_output($response);
  }
  return drupal_not_found();
}